version: '3'

services:
  my-webserver:
    image: nginx
    links:
      - my-php-server:php
    ports:
      - 80:80
    volumes:
      - ./volumes/:/var/www/html/
      - ./site.conf:/etc/nginx/conf.d/default.conf
  my-php-server:
    build: ./php/.
    volumes:
      - ./volumes/:/var/www/html/